### ISSUE TITLE
Timestamp unit for time to end

### ISSUE THREAD

**Issue by steuerlexi** [albaintor/homeassistant_electrolux_status#71]
Is it possible to have a timestamp entity for the time_to_end entity? 

I would need it for this timer bar to work:
https://github.com/rianadon/timer-bar-card

**Comment by kingy444** [comment]
The api isnt super consistent across device types - i think the easiest path forward would be to look at creating an automation that fills a timer entity for your needs

This is not super useful for my fridge, as all the timers return in minutes. This resukts in every refresh restarting the timer and it goes up and down over and overuntil the full minute passed

something like the below
```
timer:
  fridge_fast_mode:
    duration: "00:00:00"
```

```
automation:
  - alias: Set fridge fast mode timer
    trigger:
      - platform: state
        entity_id: sensor.electrolux_kitchen_fridge_fridge_fastmodetimetoend
    condition:
      - condition: template
        value_template: "{{ states('sensor.electrolux_kitchen_fridge_fridge_fastmodetimetoend') | int > 0 }}"
    action:
      - service: timer.start
        target:
          entity_id: timer.fridge_fast_mode
        data:
          duration: >
            {% set minutes = states('sensor.electrolux_kitchen_fridge_fridge_fastmodetimetoend') | int %}
            {% set hours = (minutes // 60) %}
            {% set remaining_minutes = minutes % 60 %}
            {{ '%02d:%02d:00' | format(hours, remaining_minutes) }}

```
